# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/samthomas/.oh-my-zsh"

# theme name
ZSH_THEME="sammythomas"

# add custom completions to fpath
fpath=($ZSH/custom/completions $fpath)

# plugins
plugins=(
  git-prompt-custom
  colored-man-pages
  better-vim
  up-dir
  fzf
  zsh-syntax-highlighting
)

# oh my zsh stuff
source $ZSH/oh-my-zsh.sh

# User configuration
####### Alias #######
source ~/.zshalias
####### Alias #######

highlight () {
  grep -E "$1|$"
}

loop() {
  while [ 1 = 1 ]; do
    echo "--------------"
    "$@"
  done
}

function remake() {
  rm -f $1
  make $1
}

function batch-mv() {
  for f in ${1}*; do
    mv $f ${f/#${1}/${2}}
  done
}

function batch-cp() {
  for f in ${1}*; do
    cp $f ${f/#${1}/${2}}
  done
}

# clear screen thing
clear-screen() { echoti clear; zle redisplay; }
zle -N clear-screen

###### custom project commands setup ######
source ~/.zshprojects
function proj-new() {
  if [ ! -z $1 ]; then
    echo "hash -d $1=$PWD" >> ~/.zshprojects
    source ~/.zshprojects
  else;
    echo "Need name!"
  fi
}

# fh - repeat history
# function _fh {
#   print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -r 's/ *[0-9]*\*? *//' | sed -r 's/\\/\\\\/g')
# }

# zle -N _fh
# bindkey "^r" _fh

### local zsh stuff
source ~/.zshlocal

source /home/samthomas/.config/broot/launcher/bash/br

autoload -U compinit && compinit
